main_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('tasks/', include('tracker.urls')),
    path('admin/', admin.site.urls),
]

tracker/urls.py
from django.urls import path

from . import views

app_name = 'tracker'
urlpatterns = [
    path("", views.TaskListView.as_view(), name='task-list'),
    path("<int:pk>/", views.TaskDetailView.as_view(), name='task-detail'),
    path("worker/", views.WorkerListView.as_view(), name='worker-list'),
    path("worker/<int:pk>/", views.WorkerDetailView.as_view(), name='worker-detail'),
    path("new/", views.newTaskApi, name='new-task'),
    path("edit/<int:task_id>/", views.editTaskApi, name='edit-task'),
    path("delete/<int:task_id>/", views.deleteTaskApi, name='delete-task'),
    path("worker/new/", views.newWorkerApi, name='new-worker'),
    path("worker/edit/<int:worker_id>/", views.editWorkerApi, name='edit-worker'),
    path("worker/delete/<int:worker_id>/", views.deleteWorkerApi, name='delete-worker'),
    path("<int:day>/<int:month>/", views.FilterDateView.as_view(), name='task-filter-date')
]

tracker/models.py
from django.db import models

# Create your models here.
class Worker(models.Model):
	title = models.CharField(max_length=200)
	
	def __str__(self):
		return self.title
    
class Task(models.Model):
	receiver = models.ForeignKey(Worker, on_delete=models.CASCADE)
	pub_date = models.DateTimeField("Дата создания")
	due_date = models.DateTimeField("Дата дедлайна")
	status = models.CharField(max_length=10) # created, received, done, deleted
	title = models.CharField(max_length=200,default='')
	desc = models.CharField(max_length=1000,default='')

	def __str__(self):
		return self.title

tracker/views.py
from django.http import HttpResponse
from .models import Task, Worker
from django.shortcuts import get_list_or_404, render, get_object_or_404
from django.db.models import F
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

class TaskListView(generic.ListView):
    template_name = 'tracker/task_list.html'
    context_object_name = 'tasks'
    queryset = Task.objects.all()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['workers'] = Worker.objects.all()
        return context

class TaskDetailView(generic.DetailView):
    model = Task
    template_name = 'tracker/task_detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['workers'] = Worker.objects.all()
        return context

#region task api

def newTaskApi(request):
    worker = get_object_or_404(Worker, pk=int(request.POST['receiver']))
    worker.task_set.create(
        pub_date=timezone.now(),
        due_date=request.POST['due_date'],
        status=request.POST['status'],
        title=request.POST['title'],
        desc=request.POST['desc'],
        )
    worker.save()
    return HttpResponseRedirect(reverse("tracker:task-list"))
  
def editTaskApi(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    task.desc = request.POST['desc']
    task.due_date=request.POST['due_date']
    task.status=request.POST['status']
    task.title=request.POST['title']
    task.desc=request.POST['desc']
    worker = get_object_or_404(Worker, pk=int(request.POST['receiver']))
    task.receiver = worker
    task.save()
    return HttpResponseRedirect(reverse("tracker:task-list"))

def deleteTaskApi(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    task.status = 'deleted'
    task.save()
    return HttpResponseRedirect(reverse("tracker:worker-detail", args=(task.receiver.pk)))

#endregion

class WorkerListView(generic.ListView):
    template_name = 'tracker/worker_list.html'
    context_object_name = 'workers'
    queryset = Worker.objects.all()

class WorkerDetailView(generic.DetailView):
    model = Worker
    template_name = 'tracker/worker_detail.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['workers'] = Worker.objects.all()
        return context

#region workers api

def newWorkerApi(request):
    worker = Worker(title = request.POST['title'])
    worker.save()
    return HttpResponseRedirect(reverse("tracker:worker-list"))

def editWorkerApi(request, worker_id):
    worker = get_object_or_404(Worker, pk=worker_id)
    worker.title = request.POST['title']
    worker.save()
    return HttpResponseRedirect(reverse("tracker:worker-detail", args=(worker.id)))

def deleteWorkerApi(request, worker_id):
    worker = get_object_or_404(Worker, pk=worker_id)
    worker.delete()
    return HttpResponseRedirect(reverse("tracker:worker-list", args=(worker.id)))
    
#endregion

class FilterDateView(generic.ListView):
    model = Task
    template_name = 'tracker/task_list.html'
    context_object_name = 'tasks'
    def get_queryset(self):
        return Task.objects.filter(due_date__day=self.kwargs['day']).filter(due_date__month=self.kwargs['month'])

tracker/templates/tracker/task_detail.html
<!DOCTYPE html>
<html>
  <head>
    <style>
      body {
        padding: 2rem;
        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
      }
      .form {
        border-radius: 1rem;
        background-color: #ddf;
        width: 20rem;
        font-size: 1.125rem;
        line-height: 1.75rem;
        padding-top: 0.5rem;
        padding-bottom: 1rem;
      }
      fieldset {
        border: 0;
        width: auto;
      }
      .form-group {
        display: flex;
        justify-content: space-between;
      }
      .form-required {
        color: #f44;
        font-weight: 600;
      }
      .form-submit {
        display: block;
        width: 50%;
        height: 2rem;
        font-size: 1.25rem;
        line-height: 1.75rem;
        margin-right: auto;
        margin-left: auto;
      }
      .form-textarea-label{
        align-self: center;
      }
    </style>
  </head>

  <body>
    {% if task %}
      <form action="{% url 'tracker:edit-task' task.id %}" class="form" method="post">
        {% csrf_token %}
        <fieldset class="fieldset">
          <div class="form-text form-group field-title">
            <label for="title" class="form-text-label">Название<span class="form-required">*</span></label>
            <input type="text" class="form-control" value="{{ task.title }}" name="title" access="false" maxlength="200" id="title" required="required" aria-required="true" />
          </div>
          <hr style="width: 90%;" />
          <div class="form-textarea form-group field-desc">
            <label for="desc" class="form-textarea-label">Описание</label>
            <textarea type="textarea" class="form-control" name="desc" access="false" maxlength="1000" id="desc">{{ task.desc }}</textarea>
          </div>
          <hr style="width: 90%;" />
          <div class="form-select form-group field-status">
            <label for="status" class="form-select-label">Статус</label>
            <select class="form-control" name="status" id="status" required="required" aria-required="true">
              <option value="created" {% if task.status == 'created' %}selected="true"{% endif %} id="status-0">Создана</option>
              <option value="received" {% if task.status == 'received' %}selected="true"{% endif %} id="status-1">Получена</option>
              <option value="done" {% if task.status == 'done' %}selected="true"{% endif %} id="status-2">Закончена</option>
              <option value="deleted" {% if task.status == 'deleted' %}selected="true"{% endif %} id="status-3">Удалена</option>
            </select>
          </div>
          <hr style="width: 90%;" />
          <div class="form-select form-group field-receiver">
            <label for="receiver" class="form-select-label">Исполнитель</label>
            <select class="form-control" name="receiver" id="receiver" required="required" aria-required="true">
              {% for worker in workers %}
                <option value="{{ worker.id }}" id="{{ worker.id }}">{{ worker }}</option>
              {% endfor %}
            </select>
          </div>
          <hr style="width: 90%;" />
          <div class="form-date form-group field-due_date">
            <label for="due_date" class="form-date-label">Дедлайн</label>
            <input type="date" class="form-control" name="due_date" value="{{ task.due_date|date:'Y-m-d' }}" access="false" id="due_date" required="required" aria-required="true" />
          </div>
        </fieldset>
        <input class="form-submit" type="submit" value="Сохранить" />
      </form>
    {% endif %}
  </body>
</html>

tracker/templates/tracker/task_list.html
<!DOCTYPE html>
<html>
  <head>
    <style>
      body {
        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
      }
      body > div {
        padding: 2rem;
      }
      .top {
        width: 100%;
        padding: 1rem;
        background-color: #ddf;
        font-size: 1.5rem;
        line-height: 1.75rem;
      }
      .grid {
        display: grid;
        grid-template-columns: repeat(8, minmax(0, 1fr));
        gap: 0.5rem;
      }
      .item {
        border-radius: 1rem;
        border-width: 2px;
        border-color: #111;
        background-color: #ddd;
      }
      .title {
        border-top-left-radius: 1rem;
        border-top-right-radius: 1rem;
        margin: 0;
        margin-top: -1rem;
        padding-top: 0.25rem;
        padding-bottom: 0.25rem;
        padding-left: 0.5rem;
        padding-right: 0.5rem;
      }
      .title > a {
        font-size: 1.5rem;
        line-height: 1.75rem;
        font-weight: 600;
        margin: 0;
      }
      .desc {
        padding: 0.5rem;
        margin: 0;
      }
      .desc > p {
        text-align: justify;
        margin: 0;
      }
      .worker {
        margin: 0;
        padding: 0.5rem;
      }
      .worker > p {
        margin: 0;
        font-weight: 600;
      }
      .due {
        margin: 0;
        padding: 0.5rem;
        padding-bottom: 1rem;
      }
      .due > p {
        margin: 0;
      }
      .form {
        border-radius: 1rem;
        background-color: #ddf;
        width: 20rem;
        font-size: 1.125rem;
        line-height: 1.75rem;
        padding-top: 0.5rem;
        padding-bottom: 1rem;
      }
      fieldset {
        border: 0;
        width: auto;
      }
      .form-group {
        display: flex;
        justify-content: space-between;
      }
      .form-required {
        color: #f44;
        font-weight: 600;
      }
      .form-submit {
        display: block;
        width: 50%;
        height: 2rem;
        font-size: 1.25rem;
        line-height: 1.75rem;
        margin-right: auto;
        margin-left: auto;
      }
      .form-textarea-label {
        align-self: center;
      }
    </style>
  </head>

  <body>
    <header class="top">
      <div style="display: inline-flex;">
        <a href="{% url 'tracker:worker-list' %}">Список всех работников</a>
      </div>
    </header>
    <div class="grid">
      {% if tasks %}
        {% for task in tasks %}
          {% if task.status != 'deleted' %}
            <div class="item">
              <div class="title"
                style="background-color:{% if task.status == 'created' %}
                #faa
                {% elif task.status == 'received' %}
                #ffa
                {% else %}
                #afa
                {% endif %};">
                <a href="{% url 'tracker:task-detail' task.id %}">{{ task.title }}</a>
              </div>
              <div class="desc">
                <p>{{ task.desc }}</p>
              </div>
              <hr style="width: 90%;" />
              <div class="worker">
                <p>
                  &#128119; Исполнитель: <a href="{% url 'tracker:worker-detail' task.receiver.id %}">{{ task.receiver }}</a>
                </p>
              </div>
              <hr style="width: 90%;" />
              <div class="due">
                <p>&#128197; Срок: {{ task.due_date }}</p>
              </div>
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}

      <form action="{% url 'tracker:new-task' %}" class="form item" method="post">
        {% csrf_token %}
        <fieldset class="fieldset">
          <div class="form-text form-group field-title">
            <label for="title" class="form-text-label">Название<span class="form-required">*</span></label>
            <input type="text" class="form-control" value="{{ task.title }}" name="title" access="false" maxlength="200" id="title" required="required" aria-required="true" />
          </div>
          <hr style="width: 90%;" />
          <div class="form-textarea form-group field-desc">
            <label for="desc" class="form-textarea-label">Описание</label>
            <textarea type="textarea" class="form-control" name="desc" access="false" maxlength="1000" id="desc">{{ task.desc }}</textarea>
          </div>
          <hr style="width: 90%;" />
          <div class="form-select form-group field-status">
            <label for="status" class="form-select-label">Статус</label>
            <select class="form-control" name="status" id="status" required="required" aria-required="true">
              <option value="created" selected="true" id="status-0">Создана</option>
              <option value="received" id="status-1">Получена</option>
              <option value="done" id="status-2">Закончена</option>
              <option value="deleted" id="status-3">Удалена</option>
            </select>
          </div>
          <hr style="width: 90%;" />
          <div class="form-select form-group field-receiver">
            <label for="receiver" class="form-select-label">Исполнитель</label>
            <select class="form-control" name="receiver" id="receiver" required="required" aria-required="true">
              {% for worker in workers %}
                <option value="{{ worker.id }}" id="{{ worker.id }}">{{ worker }}</option>
              {% endfor %}
            </select>
          </div>
          <hr style="width: 90%;" />
          <div class="form-date form-group field-due_date">
            <label for="due_date" class="form-date-label">Дедлайн<span class="form-required">*</span></label>
            <input type="date" class="form-control" name="due_date" value="{{ task.due_date|date:'Y-m-d' }}" access="false" id="due_date" required="required" aria-required="true" />
          </div>
        </fieldset>
        <input class="form-submit" type="submit" value="Сохранить" />
      </form>
    </div>
  </body>
</html>

tracker/templates/tracker/worker_detail.html
<!DOCTYPE html>
<html>
  <head>
    <style>
      body {
        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
      }
      body > div {
        padding: 2rem;
      }
      .top {
        width: 100%;
        padding: 1rem;
        background-color: #ddf;
        font-size: 1.5rem;
        line-height: 1.75rem;
        display: inline-block;
      }
      .grid {
        display: grid;
        grid-template-columns: repeat(8, minmax(0, 1fr));
        gap: 0.5rem;
      }
      .item {
        border-radius: 1rem;
        border-width: 2px;
        border-color: #111;
        background-color: #ddd;
      }
      .title {
        border-top-left-radius: 1rem;
        border-top-right-radius: 1rem;
        margin: 0;
        margin-top: -1rem;
        padding-top: 0.25rem;
        padding-bottom: 0.25rem;
        padding-left: 0.5rem;
        padding-right: 0.5rem;
      }
      .title > a {
        font-size: 1.5rem;
        line-height: 1.75rem;
        font-weight: 600;
        margin: 0;
      }
      .desc {
        padding: 0.5rem;
        margin: 0;
      }
      .desc > p {
        text-align: justify;
        margin: 0;
      }
      .worker {
        margin: 0;
        padding: 0.5rem;
      }
      .worker > p {
        margin: 0;
        font-weight: 600;
      }
      .due {
        margin: 0;
        padding: 0.5rem;
        padding-bottom: 1rem;
      }
      .due > p {
        margin: 0;
      }
      .form {
        border-radius: 1rem;
        background-color: #ddf;
        width: 20rem;
        font-size: 1.125rem;
        line-height: 1.75rem;
        padding-top: 0.5rem;
        padding-bottom: 1rem;
      }
      fieldset {
        border: 0;
        width: auto;
      }
      .form-group {
        display: flex;
        justify-content: space-between;
      }
      .form-required {
        color: #f44;
        font-weight: 600;
      }
      .form-submit {
        display: block;
        width: 50%;
        height: 2rem;
        font-size: 1.25rem;
        line-height: 1.75rem;
        margin-right: auto;
        margin-left: auto;
      }
      .form-textarea-label {
        align-self: center;
      }
    </style>
  </head>

  <body>
    {% if worker %}
      <header class="top">
        <div style="display: inline-flex;">
          <a href="{% url 'tracker:worker-list' %}">Список всех работников</a>
        </div>
        <p>{{ worker }}</p>
      </header>
      <div class="grid">
        {% if worker.task_set %}
          {% for task in worker.task_set.all %}
            {% if task.status != 'deleted' %}
              <div class="item">
                <div class="title"
                  style="background-color:{% if task.status == 'created' %}
                  #faa
                  {% elif task.status == 'received' %}
                  #ffa
                  {% else %}
                  #afa
                  {% endif %};">
                  <a href="{% url 'tracker:task-detail' task.id %}">{{ task.title }}</a>
                </div>
                <div class="desc">
                  <p>{{ task.desc }}</p>
                </div>
                <hr style="width: 90%;" />
                <div class="worker">
                  <p>
                    &#128119; Исполнитель: <a href="{% url 'tracker:worker-detail' task.receiver.id %}">{{ task.receiver }}</a>
                  </p>
                </div>
                <hr style="width: 90%;" />
                <div class="due">
                  <p>&#128197; Срок: {{ task.due_date }}</p>
                </div>
              </div>
            {% endif %}
          {% endfor %}
        {% endif %}

        <form action="{% url 'tracker:new-task' %}" class="form item" method="post">
          {% csrf_token %}
          <fieldset class="fieldset">
            <div class="form-text form-group field-title">
              <label for="title" class="form-text-label">Название<span class="form-required">*</span></label>
              <input type="text" class="form-control" value="{{ task.title }}" name="title" access="false" maxlength="200" id="title" required="required" aria-required="true" />
            </div>
            <hr style="width: 90%;" />
            <div class="form-textarea form-group field-desc">
              <label for="desc" class="form-textarea-label">Описание</label>
              <textarea type="textarea" class="form-control" name="desc" access="false" maxlength="1000" id="desc">{{ task.desc }}</textarea>
            </div>
            <hr style="width: 90%;" />
            <div class="form-select form-group field-status">
              <label for="status" class="form-select-label">Статус</label>
              <select class="form-control" name="status" id="status" required="required" aria-required="true">
                <option value="created" selected="true" id="status-0">Создана</option>
                <option value="received" id="status-1">Получена</option>
                <option value="done" id="status-2">Закончена</option>
                <option value="deleted" id="status-3">Удалена</option>
              </select>
            </div>
            <hr style="width: 90%;" />
            <div class="form-select form-group field-receiver">
              <label for="receiver" class="form-select-label">Исполнитель</label>
              <select class="form-control" name="receiver" id="receiver" required="required" aria-required="true">
                {% for worker in workers %}
                  <option value="{{ worker.id }}" id="{{ worker.id }}">{{ worker }}</option>
                {% endfor %}
              </select>
            </div>
            <hr style="width: 90%;" />
            <div class="form-date form-group field-due_date">
              <label for="due_date" class="form-date-label">Дедлайн<span class="form-required">*</span></label>
              <input type="date" class="form-control" name="due_date" value="{{ task.due_date|date:'Y-m-d' }}" access="false" id="due_date" required="required" aria-required="true" />
            </div>
          </fieldset>
          <input class="form-submit" type="submit" value="Сохранить" />
        </form>
      </div>
    {% endif %}
  </body>
</html>

tracker/templates/tracker/worker_list.html
<!DOCTYPE html>
<html>
  <head>
    <style>
      body {
        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
      }
      body > div {
        padding: 2rem;
      }
      .top {
        width: 100%;
        padding: 1rem;
        background-color: #ddf;
        font-size: 1.5rem;
        line-height: 1.75rem;
      }
      .grid {
        display: grid;
        grid-template-columns: repeat(8, minmax(0, 1fr));
        gap: 0.5rem;
      }
      .item {
        border-radius: 1rem;
        border-width: 2px;
        border-color: #111;
        background-color: #ddd;
      }
      .worker {
        margin: 0;
        padding: 0.5rem;
        display: flex;
        justify-content: space-between;
      }
      .worker > p {
        margin: 0;
        font-weight: 600;
      }
      .form {
        border-radius: 1rem;
        background-color: #ddf;
        width: 20rem;
        font-size: 1.125rem;
        line-height: 1.75rem;
        padding-top: 0.5rem;
        padding-bottom: 1rem;
      }
      fieldset {
        border: 0;
        width: auto;
      }
      .form-group {
        display: flex;
        justify-content: space-between;
      }
      .form-required {
        color: #f44;
        font-weight: 600;
      }
      .form-submit {
        display: block;
        width: 50%;
        height: 2rem;
        font-size: 1.25rem;
        line-height: 1.75rem;
        margin-right: auto;
        margin-left: auto;
      }
      .form-textarea-label {
        align-self: center;
      }
    </style>
  </head>

  <body>
    <header class="top">
      <div style="display: inline-flex;">
        <a href="{% url 'tracker:task-list' %}">Список всех задач</a>
      </div>
    </header>
    <div class="grid">
      {% if workers %}
        {% for worker in workers %}
          <div class="item">
            <div class="worker">
              <p>
                &#128119;<a href="{% url 'tracker:worker-detail' worker.id %}">{{ worker }}</a>
              </p>
              <form action="{% url 'tracker:delete-worker' worker.id %}">
                <input type="submit" value="&#10060" />
              </form>
            </div>
          </div>
        {% endfor %}
      {% endif %}
      <form class="item form" action="{% url 'tracker:new-worker' %}" method="post">
        {% csrf_token %}
        <fieldset>
          <div class="form-text form-group field-title">
            <label for="title" class="form-text-label">Имя<span class="form-required">*</span></label>
            <input type="text" class="form-control" value="{{ task.title }}" name="title" access="false" maxlength="200" id="title" required="required" aria-required="true" />
          </div>
        </fieldset>
        <input class="form-submit" type="submit" value="Добавить" />
      </form>
    </div>
  </body>
</html>